CREATE TABLE companies (
                           id              BIGSERIAL PRIMARY KEY,
                           company_name    VARCHAR(100) NOT NULL,
                           company_email   VARCHAR(255) NOT NULL,
                           CONSTRAINT uq_companies_company_name UNIQUE (company_name)
);

CREATE TABLE app_users (
                           id              BIGSERIAL PRIMARY KEY,
                           username        VARCHAR(255) NOT NULL,
                           email           VARCHAR(255) NOT NULL,
                           first_name      VARCHAR(100) NOT NULL,
                           last_name       VARCHAR(100) NOT NULL,
                           password        VARCHAR(255) NOT NULL,
                           role            VARCHAR(50)  NOT NULL,
                           company_id      BIGINT       NOT NULL,
                           CONSTRAINT uq_app_users_email UNIQUE (email),
                           CONSTRAINT fk_app_users_company FOREIGN KEY (company_id)
                               REFERENCES companies (id) ON DELETE CASCADE
);

CREATE INDEX idx_app_users_company_id ON app_users (company_id);

CREATE TABLE clients (
                         id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         email       VARCHAR(255),
                         first_name  VARCHAR(100) NOT NULL,
                         last_name   VARCHAR(100) NOT NULL,
                         phone       VARCHAR(50)  NOT NULL,
                         created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         update_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         status      VARCHAR(50)  NOT NULL,
                         company_id  BIGINT       NOT NULL,
                         user_id     BIGINT       NOT NULL,

                         CONSTRAINT fk_clients_company
                             FOREIGN KEY (company_id) REFERENCES companies (id),
                         CONSTRAINT fk_clients_user
                             FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE RESTRICT
);

CREATE INDEX idx_clients_company_id ON clients (company_id);
CREATE INDEX idx_clients_user_id ON clients (user_id);