CREATE TABLE client_note (
                             id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             text            TEXT NOT NULL,
                             created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             owner_note_id   BIGINT NOT NULL,
                             client_id       BIGINT NOT NULL,

                             CONSTRAINT fk_client_note_owner
                                 FOREIGN KEY (owner_note_id) REFERENCES app_users (id) ON DELETE RESTRICT,
                             CONSTRAINT fk_client_note_client
                                 FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE
);

CREATE INDEX idx_client_note_owner_id ON client_note (owner_note_id);
CREATE INDEX idx_client_note_client_id ON client_note (client_id);